###############################################################################
# Package: humidity_intelligence.yaml
# Versions:v1.1.0
# Humidity Intelligence – core backend
# - House average humidity + comfort band
# - 7-day drift
# - Worst-room condensation + mould with risk levels
# - Danger binary_sensors for badge highlighting
# - Helper for expanding the "Humidity Constellation" chart
###############################################################################

########################################
# Helpers
########################################
input_boolean:
  humidity_constellation_expanded:
    name: Humidity Constellation Expanded
    icon: mdi:chevron-down-circle

########################################
# Statistics – 7-day mean of house humidity
########################################
sensor:
  - platform: statistics
    name: House Humidity Mean 7d
    entity_id: sensor.house_average_humidity
    state_characteristic: mean
    max_age:
      days: 7

########################################
# Template sensors + binary sensors
########################################
template:
  - sensor:
      #########################################################################
      # CONFIGURATION - Define ALL potential rooms here.
      # The logic below is dynamic: if a sensor listed here doesn't exist 
      # or is unavailable, it will be automatically ignored.
      #########################################################################
      - name: Humidity Intelligence Config
        unique_id: humidity_intelligence_config
        state: "Active"
        attributes:
          room_map: >
            {# >>> MAP COMMON ROOMS TO DEFAULT SENSOR NAMES <<< #}
            {{ {
              'Living Room':    'sensor.living_room_humidity',
              'Kitchen':        'sensor.kitchen_humidity',
              'Dining Room':    'sensor.dining_room_humidity',
              'Master Bedroom': 'sensor.master_bedroom_humidity',
              'Bedroom 1':      'sensor.bedroom_1_humidity',
              'Bedroom 2':      'sensor.bedroom_2_humidity',
              'Kids Room':      'sensor.kids_room_humidity',
              'Guest Room':     'sensor.guest_room_humidity',
              'Office':         'sensor.office_humidity',
              'Study':          'sensor.study_humidity',
              'Main Bathroom':  'sensor.main_bathroom_humidity',
              'Ensuite':        'sensor.ensuite_humidity',
              'Toilet':         'sensor.toilet_humidity',
              'Laundry Room':   'sensor.laundry_room_humidity',
              'Hallway':        'sensor.hallway_humidity',
              'Entrance':       'sensor.entrance_humidity',
              'Mudroom':        'sensor.mudroom_humidity',
              'Playroom':       'sensor.playroom_humidity',
              'Garage':         'sensor.garage_humidity',
              'Basement':       'sensor.basement_humidity',
              'Attic':          'sensor.attic_humidity',
              'Pantry':         'sensor.pantry_humidity',
              'Sunroom':        'sensor.sunroom_humidity'
            } }}

      #########################################################################
      # House average humidity
      #########################################################################
      - name: House Average Humidity
        unique_id: humidity_intelligence_house_average
        unit_of_measurement: "%"
        device_class: humidity
        state_class: measurement
        state: >
          {# Retrieve the map from the config sensor #}
          {% set room_map = state_attr('sensor.humidity_intelligence_config', 'room_map') %}
          
          {# DYNAMIC FILTER: Get values only from sensors that actually exist and have data #}
          {% set entities = room_map.values() | select('has_value') | list %}

          {# Filter usable numbers and convert to a list of floats #}
          {% set vals = expand(entities) 
                        | map(attribute='state') 
                        | select('is_number') 
                        | map('float') 
                        | list %}

          {% if vals | length == 0 %}
            {# No usable data yet – reuse last numeric value (or 0 on first boot) #}
            {{ states(this.entity_id) | float(0) }}
          {% else %}
            {{ (vals|sum / vals|length)|round(1) }}
          {% endif %}

      #########################################################################
      # Comfort band targets – adjust if you prefer different limits
      #########################################################################
      - name: House Humidity Target Low
        unique_id: humidity_intelligence_target_low
        unit_of_measurement: "%"
        state: 45

      - name: House Humidity Target High
        unique_id: humidity_intelligence_target_high
        unit_of_measurement: "%"
        state: 55

      #########################################################################
      # 7-day drift: current average vs 7-day mean
      #########################################################################
      - name: House Humidity Drift 7d
        unique_id: humidity_intelligence_drift_7d
        unit_of_measurement: "%"
        state: >
          {% set current = states('sensor.house_average_humidity')|float(0) %}
          {% set mean = states('sensor.house_humidity_mean_7d')|float(0) %}
          {{ (current - mean)|round(1) }}

      #########################################################################
      # Worst-room condensation
      #   - state = room name
      #   - attributes: humidity, risk
      #########################################################################
      - name: Worst Room Condensation
        unique_id: humidity_intelligence_worst_condensation_room
        state: >
          {# Retrieve the map from the config sensor #}
          {% set rooms = state_attr('sensor.humidity_intelligence_config', 'room_map') %}
          {# Initialize a namespace to persist data outside the loop #}
          {% set ns = namespace(max_room='Unknown', max_val=0) %}
          
          {% for name, entity_id in rooms.items() %}
            {# DYNAMIC CHECK: Skip if sensor is missing or unavailable #}
            {% if has_value(entity_id) %}
              {% set val = states(entity_id)|float(0) %}
              {% if val > ns.max_val %}
                {% set ns.max_val = val %}
                {% set ns.max_room = name %}
              {% endif %}
            {% endif %}
          {% endfor %}
          {{ ns.max_room }}
        attributes:
          humidity: >
            {% set rooms = state_attr('sensor.humidity_intelligence_config', 'room_map') %}
            {% set ns = namespace(max_val=0) %}
            
            {% for name, entity_id in rooms.items() %}
              {% if has_value(entity_id) %}
                {% set val = states(entity_id)|float(0) %}
                {% if val > ns.max_val %}
                  {% set ns.max_val = val %}
                {% endif %}
              {% endif %}
            {% endfor %}
            {{ ns.max_val|round(1) }}
          risk: >
            {% set h = state_attr('sensor.worst_room_condensation', 'humidity')|float(0) %}
            {% if h >= 80 %}
              Danger
            {% elif h >= 70 %}
              Risk
            {% elif h >= 60 %}
              Watch
            {% else %}
              Low
            {% endif %}

      - name: Worst Room Condensation Risk
        unique_id: humidity_intelligence_worst_condensation_risk
        state: >
          {{ state_attr('sensor.worst_room_condensation', 'risk') or 'Unknown' }}

      #########################################################################
      # Worst-room mould
      #   - state = room name
      #   - attributes: humidity, risk
      #########################################################################
      - name: Worst Room Mould
        unique_id: humidity_intelligence_worst_mould_room
        state: >
          {% set rooms = state_attr('sensor.humidity_intelligence_config', 'room_map') %}
          {% set ns = namespace(max_room='Unknown', max_val=0) %}
          
          {% for name, entity_id in rooms.items() %}
            {% if has_value(entity_id) %}
              {% set val = states(entity_id)|float(0) %}
              {% if val > ns.max_val %}
                {% set ns.max_val = val %}
                {% set ns.max_room = name %}
              {% endif %}
            {% endif %}
          {% endfor %}
          {{ ns.max_room }}
        attributes:
          humidity: >
            {% set rooms = state_attr('sensor.humidity_intelligence_config', 'room_map') %}
            {% set ns = namespace(max_val=0) %}
            
            {% for name, entity_id in rooms.items() %}
              {% if has_value(entity_id) %}
                {% set val = states(entity_id)|float(0) %}
                {% if val > ns.max_val %}
                  {% set ns.max_val = val %}
                {% endif %}
              {% endif %}
            {% endfor %}
            {{ ns.max_val|round(1) }}
          risk: >
            {% set h = state_attr('sensor.worst_room_mould', 'humidity')|float(0) %}
            {% if h >= 75 %}
              Danger
            {% elif h >= 65 %}
              Risk
            {% elif h >= 55 %}
              Watch
            {% else %}
              Low
            {% endif %}

      - name: Worst Room Mould Risk
        unique_id: humidity_intelligence_worst_mould_risk
        state: >
          {{ state_attr('sensor.worst_room_mould', 'risk') or 'Unknown' }}

  - binary_sensor:
      #########################################################################
      # Binary flags used to highlight badges
      #########################################################################
      - name: Humidity Danger
        unique_id: humidity_intelligence_humidity_danger
        device_class: problem
        state: >
          {% set h = states('sensor.house_average_humidity')|float(0) %}
          {% set low = states('sensor.house_humidity_target_low')|float(45) %}
          {% set high = states('sensor.house_humidity_target_high')|float(55) %}
          {% set cond_risk = state_attr('sensor.worst_room_condensation', 'risk') %}
          {% set mould_risk = state_attr('sensor.worst_room_mould', 'risk') %}
          {{ (h < low - 10) or (h > high + 10) or cond_risk == 'Danger' or mould_risk == 'Danger' }}

      - name: Condensation Danger
        unique_id: humidity_intelligence_condensation_danger
        device_class: problem
        state: >
          {% set risk = state_attr('sensor.worst_room_condensation', 'risk') %}
          {{ risk in ['Risk', 'Danger'] }}

      - name: Mould Danger
        unique_id: humidity_intelligence_mould_danger
        device_class: problem
        state: >
          {% set risk = state_attr('sensor.worst_room_mould', 'risk') %}
          {{ risk in ['Risk', 'Danger'] }}

  - sensor:
      #########################################################################
      # Series used to populate Humidity Constellation Card
      #########################################################################
      - name: "Humidity Constellation Series"
        state: "ok"
        attributes:
          series: >
            {% set rooms = state_attr('sensor.humidity_intelligence_config', 'room_map') %}
            {% set ns = namespace(result=[]) %}
            {% if rooms %}
              {% for name, entity in rooms.items() %}
                {% if has_value(entity) %}
                  {% set ns.result = ns.result + [{
                    'entity': entity,
                    'name': name,
                    'type': 'line',
                    'curve': 'smooth',
                    'stroke_width': 2,
                    'group_by': {
                      'func': 'avg',
                      'duration': '15min'
                    }
                  }] %}
                {% endif %}
              {% endfor %}
            {% endif %}
            {{ ns.result }}